put "1" color (red) 
put "2" color (blue) 
put "3" color (green)
put "4" color (yellow)
put "5" color (purple)
put "6"
put "7" color (blue)
put "8" color (green)
put "9" color (red)
put "10" color (yellow)
put "11" color (purple)
put "12" color (grey)
put "13" color (green)
put "14" color (red)
put "15" color (blue)
